# PANDAS IN PYTHON

## SERIES

In [3]:
import numpy as np

In [5]:
import pandas as pd

In [7]:
my_data = [10,20,30]
labels = ['a','b','c']
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [9]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(data = my_data,index = labels)

a    10
b    20
c    30
dtype: int64

In [13]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [15]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [17]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [19]:
ser1=pd.Series([1,2,3,4],['USA','INDIA','JAPAN','FRANCE'])
ser2=pd.Series([1,2,5,7],['USA','ITLY','JAPAN','FRANCE'])

In [21]:
ser1

USA       1
INDIA     2
JAPAN     3
FRANCE    4
dtype: int64

In [23]:
ser2

USA       1
ITLY      2
JAPAN     5
FRANCE    7
dtype: int64

In [25]:
ser1['JAPAN']

3

In [27]:
ser1+ser2

FRANCE    11.0
INDIA      NaN
ITLY       NaN
JAPAN      8.0
USA        2.0
dtype: float64

## DATAFRAME

In [1]:
import numpy as np
import pandas as pd

In [3]:
from numpy.random import randn

In [5]:
np.random.seed(101)

In [7]:
df = pd.DataFrame(randn(6,5),['A','B','C','D','E','F',],['V','W','X','Y','Z'])

In [9]:
df

          V         W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [11]:
df['X']

A    0.907969
B    0.605965
C    0.188695
D    1.978757
E   -1.706086
F    0.184502
Name: X, dtype: float64

In [13]:
type(df['X'])

pandas.core.series.Series

In [15]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df[['W','Z']]

          W         Z
A  0.628133  0.651118
B -0.848077  0.740122
C -0.589001 -0.933237
D  0.190794  0.683509
E  1.693723 -0.134841
F  0.166905  0.072960

In [23]:
df['new']=df['V'] + df['Y']     # to add column !

In [25]:
df

          V         W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  0.651118  3.210676
B -0.319318 -0.848077  0.605965 -2.018168  0.740122 -2.337486
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237 -0.230059
D  0.955057  0.190794  1.978757  2.605967  0.683509  3.561024
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841 -0.856454
F  0.390528  0.166905  0.184502  0.807706  0.072960  1.198234

In [29]:
df.drop('new',axis=1)     #temporary remove of column !

          V         W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [31]:
df

          V         W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  0.651118  3.210676
B -0.319318 -0.848077  0.605965 -2.018168  0.740122 -2.337486
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237 -0.230059
D  0.955057  0.190794  1.978757  2.605967  0.683509  3.561024
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841 -0.856454
F  0.390528  0.166905  0.184502  0.807706  0.072960  1.198234

In [33]:
df.drop('new',axis=1,inplace=True)     # Permenant remove of column !

In [35]:
df

          V         W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [39]:
df.drop('C',axis=0)

          V         W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [41]:
df

          V         W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [47]:
df.loc['A']    #Grabbing rows by name !

V    2.706850
W    0.628133
X    0.907969
Y    0.503826
Z    0.651118
Name: A, dtype: float64

In [49]:
df.iloc[2]      #Grabbing rows by index number !

V    0.528813
W   -0.589001
X    0.188695
Y   -0.758872
Z   -0.933237
Name: C, dtype: float64

In [53]:
df.loc['E','X']      # Grabbing perticular element!

-1.7060859307350775

In [57]:
df.loc[['A','C','E'],['W','Y']]

          W         Y
A  0.628133  0.503826
C -0.589001 -0.758872
E  1.693723 -1.159119

In [59]:
## conditional selections !

In [61]:
df >0

       V      W      X      Y      Z
A   True   True   True   True   True
B  False  False   True  False   True
C   True  False   True  False  False
D   True   True   True   True   True
E   True   True  False  False  False
F   True   True   True   True   True

In [63]:
df_bool = df>0

In [65]:
df[df_bool]

          V         W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826  0.651118
B       NaN       NaN  0.605965       NaN  0.740122
C  0.528813       NaN  0.188695       NaN       NaN
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723       NaN       NaN       NaN
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [67]:
df['W']>0

A     True
B    False
C    False
D     True
E     True
F     True
Name: W, dtype: bool

In [69]:
df['W']

A    0.628133
B   -0.848077
C   -0.589001
D    0.190794
E    1.693723
F    0.166905
Name: W, dtype: float64

In [71]:
df[df['W']>0]

          V         W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826  0.651118
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [73]:
df[df['V']<0]

          V         W         X         Y         Z
B -0.319318 -0.848077  0.605965 -2.018168  0.740122

In [75]:
result = df[df['W']>0]

In [77]:
result

          V         W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826  0.651118
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [79]:
result['X']

A    0.907969
D    1.978757
E   -1.706086
F    0.184502
Name: X, dtype: float64

In [83]:
df[df['W']>0]['X']    # in one line !

A    0.907969
D    1.978757
E   -1.706086
F    0.184502
Name: X, dtype: float64

In [87]:
df[df['W']>0][['X','Y']]

          X         Y
A  0.907969  0.503826
D  1.978757  2.605967
E -1.706086 -1.159119
F  0.184502  0.807706

In [107]:
bool_ser = df['W']>0
result = df[bool_ser]
my_col = ['X','Y']
final = result[my_col]

In [109]:
final

          X         Y
A  0.907969  0.503826
D  1.978757  2.605967
E -1.706086 -1.159119
F  0.184502  0.807706

In [111]:
df[(df['W']>0) & (df['X']<0)]

          V         W         X         Y         Z
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [113]:
df[(df['W']<0) | (df['X']<0)]

          V         W         X         Y         Z
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [115]:
df.reset_index()

  index         V         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826  0.651118
1     B -0.319318 -0.848077  0.605965 -2.018168  0.740122
2     C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
3     D  0.955057  0.190794  1.978757  2.605967  0.683509
4     E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
5     F  0.390528  0.166905  0.184502  0.807706  0.072960

In [117]:
df

          V         W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [125]:
new_ind = "OA BC KC MF RO NJ".split()

In [127]:
new_ind

['OA', 'BC', 'KC', 'MF', 'RO', 'NJ']

In [137]:
df['States'] = new_ind

In [139]:
df

          V         W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826  0.651118     OA
B -0.319318 -0.848077  0.605965 -2.018168  0.740122     BC
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237     KC
D  0.955057  0.190794  1.978757  2.605967  0.683509     MF
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841     RO
F  0.390528  0.166905  0.184502  0.807706  0.072960     NJ

In [141]:
df.set_index('States')

               V         W         X         Y         Z
States
OA      2.706850  0.628133  0.907969  0.503826  0.651118
BC     -0.319318 -0.848077  0.605965 -2.018168  0.740122
KC      0.528813 -0.589001  0.188695 -0.758872 -0.933237
MF      0.955057  0.190794  1.978757  2.605967  0.683509
RO      0.302665  1.693723 -1.706086 -1.159119 -0.134841
NJ      0.390528  0.166905  0.184502  0.807706  0.072960

In [143]:
df

          V         W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826  0.651118     OA
B -0.319318 -0.848077  0.605965 -2.018168  0.740122     BC
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237     KC
D  0.955057  0.190794  1.978757  2.605967  0.683509     MF
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841     RO
F  0.390528  0.166905  0.184502  0.807706  0.072960     NJ

## Multi-Index and Index Hierarchy¶

.

In [159]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [161]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [163]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1 -1.136645  0.000366
   2  1.025984 -0.156598
   3 -0.031579  0.649826
G2 1  2.154846 -0.610259
   2 -0.755325 -0.346419
   3  0.147027 -0.479448

In [167]:
df.loc['G1'].loc[1]

A   -1.136645
B    0.000366
Name: 1, dtype: float64

In [171]:
df.loc['G1'].iloc[0]

A   -1.136645
B    0.000366
Name: 1, dtype: float64

In [178]:
df.index.names

FrozenList([None, None])

In [180]:
df.index.names = ["Group","Num"]

In [183]:
df

                  A         B
Group Num
G1    1   -1.136645  0.000366
      2    1.025984 -0.156598
      3   -0.031579  0.649826
G2    1    2.154846 -0.610259
      2   -0.755325 -0.346419
      3    0.147027 -0.479448

In [195]:
# Lets grab G2--> 2 ---> B

df.loc['G2'].loc[2]['B']

-0.34641850351854453

In [197]:
df.xs(1,level = 'Num')

              A         B
Group
G1    -1.136645  0.000366
G2     2.154846 -0.610259

## MISSING DATA

In [4]:
import numpy as np
import pandas as pd

In [6]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [8]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [12]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [14]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [16]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [18]:
df.fillna(value='VAL')

     A    B  C
0  1.0  5.0  1
1  2.0  VAL  2
2  VAL  VAL  3

In [20]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [26]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [34]:
df.loc[1].fillna(value=df.iloc[1].mean())

A    2.0
B    2.0
C    2.0
Name: 1, dtype: float64

## GROUPBY

In [39]:
import numpy as np
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [47]:
df = pd.DataFrame(data)

In [49]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [53]:
df.groupby('Company')     # created a groupby object !

In [63]:
By_comp = df.groupby('Company')

In [73]:
By_comp.sum()  # perform any aggrigate method !

             Person  Sales
Company
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [85]:
By_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [87]:
df.groupby('Company')['Sales'].mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [89]:
df.groupby('Company')['Sales'].std()

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sales, dtype: float64

In [91]:
df.groupby('Company')['Sales'].std().loc['MSFT']

152.73506473629428

In [93]:
df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [95]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

## MERGING JOINING AND CONCATENATING

In [98]:
import numpy as np
import pandas as pd

In [100]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [102]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [104]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [106]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [108]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [110]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [112]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [114]:
pd.concat([df1,df2,df3],axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [116]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [118]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [120]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [122]:
pd.merge(left,right,how = 'inner',on ='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [124]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [126]:
left

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [128]:
right

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [130]:
pd.merge(left, right, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [132]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [134]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [136]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [138]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [140]:
left

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [142]:
right

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [144]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [146]:
right.join(left)

     C   D    A    B
K0  C0  D0   A0   B0
K2  C2  D2   A2   B2
K3  C3  D3  NaN  NaN

In [148]:
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

## OPERATIONS

In [151]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [157]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [159]:
len(df['col2'].unique())

3

In [161]:
df['col2'].nunique()

3

In [163]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [165]:
def times4(x):
    return x*4

In [167]:
df['col2'].apply(times4)

0    1776
1    2220
2    2664
3    1776
Name: col2, dtype: int64

In [173]:
df['col2'].apply(lambda x : x*4)

0    1776
1    2220
2    2664
3    1776
Name: col2, dtype: int64

In [175]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [177]:
df.drop('col1',axis=1)

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [179]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [181]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [183]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [185]:
df.sort_values('col2')

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [187]:
df.sort_values('col3')

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [189]:
df.isnull()

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [191]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [193]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [195]:
df.pivot_table(values='D',index=['A','B'],columns='C')

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

## DATA INPUT OUTPUT

In [3]:
pwd

'C:\\Users\\Rohit Maity\\Desktop\\coding\\Data Science\\Code\\Pandas'

In [5]:
import pandas as pd

In [11]:
df = pd.read_csv('example')

In [13]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [15]:
df.to_csv('MY_OUTPUT',index=False)

In [17]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [31]:
df = pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

In [33]:
df

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [35]:
df.to_excel('Excel_Sample2.xlsx',sheet_name='Sheet2')

In [37]:
df

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [39]:
data = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [41]:
data

[                                            Bank Name                City  \
 0                   Metropolitan Capital Bank & Trust             Chicago
 1                        The Santa Anna National Bank          Santa Anna
 2                                Pulaski Savings Bank             Chicago
 3                  The First National Bank of Lindsay             Lindsay
 4               Republic First Bank dba Republic Bank        Philadelphia
 5                                       Citizens Bank            Sac City
 6                            Heartland Tri-State Bank             Elkhart
 7                                 First Republic Bank       San Francisco
 8                                      Signature Bank            New York
 9                                 Silicon Valley Bank         Santa Clara
 10                                  Almena State Bank              Almena
 11                         First City Bank of Florida   Fort Walton Beach
 12                               The First State Bank       Barboursville
 13                                 Ericson State Bank             Ericson
 14                   City National Bank of New Jersey              Newark
 15                                      Resolute Bank              Maumee
 16                              Louisa Community Bank              Louisa
 17                               The Enloe State Bank              Cooper
 18                Washington Federal Bank for Savings             Chicago
 19    The Farmers and Merchants State Bank of Argonia             Argonia
 20                                Fayette County Bank          Saint Elmo
 21  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 22                                     First NBC Bank         New Orleans
 23                                      Proficio Bank  Cottonwood Heights
 24                      Seaway Bank and Trust Company             Chicago

             State   Cert                Acquiring Institution  \
 0        Illinois  57488              First Independence Bank
 1           Texas   5520            Coleman County State Bank
 2        Illinois  28611                      Millennium Bank
 3        Oklahoma   4134               First Bank & Trust Co.
 4    Pennsylvania  27332    Fulton Bank, National Association
 5            Iowa   8758            Iowa Trust & Savings Bank
 6          Kansas  25851               Dream First Bank, N.A.
 7      California  59017            JPMorgan Chase Bank, N.A.
 8        New York  57053                  Flagstar Bank, N.A.
 9      California  24735  First–Citizens Bank & Trust Company
 10         Kansas  15426                          Equity Bank
 11        Florida  16748            United Fidelity Bank, fsb
 12  West Virginia  14361                       MVB Bank, Inc.
 13       Nebraska  18265           Farmers and Merchants Bank
 14     New Jersey  21111                      Industrial Bank
 15           Ohio  58317                   Buckeye State Bank
 16       Kentucky  58112    Kentucky Farmers Bank Corporation
 17          Texas  10716                   Legend Bank, N. A.
 18       Illinois  30570                   Royal Savings Bank
 19         Kansas  17719                          Conway Bank
 20       Illinois   1802            United Fidelity Bank, fsb
 21      Wisconsin  30003  First-Citizens Bank & Trust Company
 22      Louisiana  58302                         Whitney Bank
 23           Utah  35495                    Cache Valley Bank
 24       Illinois  19328                  State Bank of Texas

          Closing Date  Fund  Sort ascending
 0    January 30, 2026                 10550
 1       June 27, 2025                 10549
 2    January 17, 2025                 10548
 3    October 18, 2024                 10547
 4      April 26, 2024                 10546
 5    November 3, 2023                 10545
 6       July 28, 2023                 10544
 7         May 1, 2023                 10543
 8      March 12, 2023                 10540
 9      March 10, 2023                 10539
 10   October 23, 2020                 10538
 11   October 16, 2020                 10537
 12      April 3, 2020                 10536
 13  February 14, 2020                 10535
 14   November 1, 2019                 10534
 15   October 25, 2019                 10533
 16   October 25, 2019                 10532
 17       May 31, 2019                 10531
 18  December 15, 2017                 10530
 19   October 13, 2017                 10529
 20       May 26, 2017                 10528
 21        May 5, 2017                 10527
 22     April 28, 2017                 10526
 23      March 3, 2017                 10525
 24   January 27, 2017                 10524  ]

In [47]:
data[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [49]:
from sqlalchemy import create_engine

In [55]:
engine = create_engine('sqlite:///:memory:')

In [57]:
df.to_sql('my_table',engine)

4

In [59]:
sqldf=pd.read_sql('my_table',con=engine)

In [61]:
sqldf

   index  Unnamed: 0   a   b   c   d
0      0           0   0   1   2   3
1      1           1   4   5   6   7
2      2           2   8   9  10  11
3      3           3  12  13  14  15